version: '3'
services:
  postgres:
    image: "postgres:bullseye"
    container_name: postgres
    restart: "always"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:bullseye"
    container_name: redis
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    # ports:
    #   - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    build: "."
    restart: "always"
    container_name: app
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      - FASTAPI_HOST=${FASTAPI_HOST}
      - FASTAPI_PATH=${FASTAPI_PATH}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - FASTAPI_ORIGINS=${FASTAPI_ORIGINS}

    volumes:
      - files:/app/files
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    depends_on:
      - postgres
      - redis

volumes:
  files:
  postgres:
  redis:
